Fix `String.Format` to handle formatting of multiple types correctly, not only DateTime
Handlebars-Net/Handlebars.Net.Helpers pull request #31
Opened 2021-04-22 09:07 UTC by DamienBraillard

Hi,

First, thanks for the hard work and the great library !

I started using Handlebars.Net and the associated Handlebars.Net.Helpers because I need to format values (which Stubble can't do easily). What I need to format is an "Instant" value representing a date from the "NodaTime" library.

I was quite surprised to get an error `The method Format cannot be used on value '2001-11-21T00:00:00Z' of Type 'NodaTime.Instant'`.

Looking into the code, it seems that only DateTime is supported:
```csharp
[HandlebarsWriter(WriterType.String)]
public string Format(object value, string format)
{
    switch (value)
    {
        case DateTime dateTime:
            return dateTime.ToString(format, Context.Configuration.FormatProvider);

        default:
            throw new NotSupportedException($"The method {nameof(Format)} cannot be used on value '{value}' of Type '{value?.GetType()}'.");
    }
}
```

The method should make use of `ICustomFormatter` and `IFormattable` to format values as these interfaces are intended for this purpose (this is what the `String.Format` method uses to format string). Using these interfaces would allow formatting anything that can be like the `String.Format` method does.

Here is an example of a failing test that attempts to format a `Decimal` (But it is the same for NodaTime `Instant`):
```csharp
[Fact]
public void TestFormat()
{
    // Arrange
    var data = new { MyValue = 1.2m };
    var template = @"{{String.Format MyValue ""N2""}}";

    var x = data.MyValue.ToString("N2");
    
    // Act
    var compiledTemplate = _target.PublicGetCompiledTemplate(template);

    // Assert
    var rendered = compiledTemplate(data);
    rendered.Should().Be("1.20");
}
```

2021-04-22 15:58 UTC, DamienBraillard commented
If it's any help about the build failing, it seems that the task "Prepare analysis on SonarCloud" did not run because: "References service endpoint. PRs from repository forks are not allowed to access secrets in the pipeline. For more information see https://go.microsoft.com/fwlink/?linkid=862029"

This then caused the "SonarCloud: Run Code Analysis" task to fail because it was not prepared !

2021-04-22 16:27 UTC, StefH commented
@DamienBraillard . Thank you for the PR. I'll take a look.

About the CI-build failing, I don't know/see the difference between this CI build and this CI build (https://github.com/WireMock-Net/WireMock.Net/blob/master/azure-pipelines-ci.yml)

A PR on WireMock.Net does work correctly?
https://github.com/WireMock-Net/WireMock.Net/pull/607

2021-04-22 16:31 UTC, StefH requested changes

2021-04-22 16:31 UTC, StefH commented on src/Handlebars.Net.Helpers/Helpers/StringHelpers.cs
> +            return formattedValue ?? "";
string.Empty

2021-04-23 05:44 UTC, DamienBraillard commented on src/Handlebars.Net.Helpers/Helpers/StringHelpers.cs
> +            return formattedValue ?? "";
Done, thank you for the feedback

2021-04-23 07:41 UTC, 0xced commented
About the CI failure: The step *Prepare analysis on SonarCloud* did not run, eventually causing the *SonarCloud: Run Code Analysis* step to fail. The following [warning](https://dev.azure.com/stef/Handlebars.Net.Helpers/_build/results?buildId=4930&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=41294432-7274-5d80-86e5-6eb8000a3386) gives a hint at what is happening:
> References service endpoint. PRs from repository forks are not allowed to access secrets in the pipeline. For more information see https://go.microsoft.com/fwlink/?linkid=862029 

How is you `RUN_SONAR` [variable](https://github.com/Handlebars-Net/Handlebars.Net.Helpers/blob/d649edc1e88b077a0e316e83f03ee0521a283485/azure-pipeline-ci.yml#L25) configured? Is it marked as secret in your Azure DevOps configuration?

See the Azure Pipelines documentation on [Contributions from forks](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github#contributions-from-forks):
> By default with GitHub pipelines, **secrets associated with your build pipeline are not made available to pull request builds** of forks. These secrets are enabled by default with GitHub Enterprise Server pipelines. Secrets include:
> * A security token with access to your GitHub repository.
> * These items, if your pipeline uses them:
>   * Service connection credentials
>   * Files from the secure files library
>   * **Build [variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops#secret-variables) marked secret**

2021-04-23 07:55 UTC, StefH commented on src/Handlebars.Net.Helpers/Helpers/StringHelpers.cs
> +            return formattedValue ?? "";
Thanks

2021-04-23 07:57 UTC, StefH commented
@0xced 
No, only the MyGet key is secret, see:
![image](https://user-images.githubusercontent.com/249938/115838703-4180d800-a41a-11eb-9271-82d869112637.png)

2021-04-23 08:24 UTC, 0xced commented
The secret variables was not the cause. Searching for "PRs from repository forks are not allowed to access secrets in the pipeline" lead me to the [source code](https://github.com/microsoft/azure-pipelines-agent/blob/a376eccb668cab37c3e3bd8e6dbaa182562267c2/src/Agent.Worker/TaskRunner.cs#L248-L278) of the Azure Pipeline agent runner. And the key in this error message was this: `References service endpoint.`

Apparently, the task is skipped because you have configured [service connection](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints) credentials.

2021-04-23 08:31 UTC, StefH commented
@0xced 
For my other project, I've this set:
![image](https://user-images.githubusercontent.com/249938/115843124-cc63d180-a41e-11eb-9b41-0d6517f7061c.png)

And for this project, this checkbox is not enabled.

However, I think that enabling this checkbox is unsafe, like someone can see the secret MyGetKey ?

2021-04-23 08:37 UTC, 0xced commented
> However, I think that enabling this checkbox is unsafe, like someone can see the secret MyGetKey ?

Indeed, your secret MyGetKey could be retrieved by someone forking your repository if you make secrets available to builds of forks and you don't want that.

Do you have a [service connection](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#manage-a-service-connection) configured? I think this could be the actual cause of the skipped task. The secret variables was just red herring.

![overview-page](https://user-images.githubusercontent.com/51363/115844095-ccb09c80-a41f-11eb-924d-fc0657dccf54.png)

2021-04-23 08:44 UTC, StefH commented
Correct, I've a service connection:
![image](https://user-images.githubusercontent.com/249938/115845206-e9010900-a420-11eb-8d10-14577f3bd925.png)

2021-04-23 09:02 UTC, StefH commented
@DamienBraillard @0xced 

I think for now I'll approve + merge this PR.

And update the pipeline yml to include `ne(variables['Build.Reason'], 'PullRequest')` for the sonarcloud and myget steps

2021-04-23 09:02 UTC, merged